---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  eslint:
    enabled: true
  fixme:
    enabled: true
  nodesecurity:
    enabled: true
ratings:
  paths:
  - "src/**.js"
exclude_paths:
- dist/**/*
- test/**/*
